### ISSUE TITLE
which C standard will you use?

### ISSUE THREAD

**Issue by LemonHX** [eliphatfs/c-std-headers#1]
for compatibility I suggest you use ANSI C89 
at the same time I suggest to use less magic and wack behaviours in C89.

**Comment by eliphatfs** [comment]
Mainly C89, and have dumped much of the standard stuff already. Other versions could be made available conditionally through common macro definitions of what the compiler uses, in the future.

**Comment by eliphatfs** [comment]
However, the original C89 standard is not freely available, so I refer to the C99 standard PDF when implementing, but I will try to be conformant with C89.
